name: .NET Core CI
on: [push]

jobs:
  build:
    name: Build & PipeLine Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - name: Azure Pipelines Action
      uses: Azure/pipelines@releases/v1
      with:
        # 対象のプロジェクト名を含むAzreDevOpsの組織URL
        azure-devops-project-url: https://dev.azure.com/kokoni-labo/kokoni-githubactions
        # 対象のPipeline名
        azure-pipeline-name: githubactiontest
        # AzureDevopsのプライベートアクセストークン
        azure-devops-token: ${{secrets.AzureDevOpsToken}}
