name: .NET Core CI
on: [push]

jobs:
  build:
    name: Debug Build & Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet-version: ['3.0.100', '3.1.100']
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore Tool
      run: dotnet tool restore
    - name: Lint
      run: dotnet format --check --dry-run
    - name: Build
      run: dotnet build -c Debug SampleWebSite.csproj

  pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Azure Pipelines Action
      uses: Azure/pipelines@releases/v1
      with:
        # 対象のプロジェクト名を含むAzreDevOpsの組織URL
        azure-devops-project-url: https://dev.azure.com/kokoni-labo/kokoni-githubactions
        # 対象のPipeline名
        azure-pipeline-name: githubactiontest
        # AzureDevopsのプライベートアクセストークン
        azure-devops-token: 
  
